# Generated by Django 4.2.5 on 2023-09-10 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='current_day',
            field=models.CharField(default='Sunday', max_length=255),
        ),
        migrations.AddField(
            model_name='mydata',
            name='github_file_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mydata',
            name='github_repo_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mydata',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='mydata',
            name='utc_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='slack_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='track',
            field=models.CharField(default='backend', max_length=255),
        ),
    ]
